// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAwaW3NgKVLfQuKJiWKZ2S7Mndz5TeF5XM",
      authDomain: "lumenox-7905c.firebaseapp.com",
      projectId: "lumenox-7905c",
      storageBucket: "lumenox-7905c.firebasestorage.app",
      messagingSenderId: "213337970121",
      appId: "1:213337970121:web:a72b1e59c3119adeccc418",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFcOsISYNzPGUisySPApr_0xCmql8HHw',
    appId: '1:213337970121:android:f81594b46e40de7eccc418',
    messagingSenderId: '213337970121',
    projectId: 'lumenox-7905c',
    storageBucket: 'lumenox-7905c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFeQKCmfpqH-CQNvk2YdQZHgTLOpQMH3M',
    appId: '1:213337970121:ios:51d2eef036843e87ccc418',
    messagingSenderId: '213337970121',
    projectId: 'lumenox-7905c',
    storageBucket: 'lumenox-7905c.firebasestorage.app',
    iosBundleId: 'com.example.lumenoxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFeQKCmfpqH-CQNvk2YdQZHgTLOpQMH3M',
    appId: '1:213337970121:ios:51d2eef036843e87ccc418',
    messagingSenderId: '213337970121',
    projectId: 'lumenox-7905c',
    storageBucket: 'lumenox-7905c.firebasestorage.app',
    iosBundleId: 'com.example.lumenoxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwaW3NgKVLfQuKJiWKZ2S7Mndz5TeF5XM',
    appId: '1:213337970121:web:b224500e1c77c8bdccc418',
    messagingSenderId: '213337970121',
    projectId: 'lumenox-7905c',
    authDomain: 'lumenox-7905c.firebaseapp.com',
    storageBucket: 'lumenox-7905c.firebasestorage.app',
  );
}
